### PR TITLE
Fixing memory leaks and synchronization

### LINKED ISSUE #419: sendZeroCopy & ByteBuffer.allocateDirect issue
Issue description:
I used floowing function to send data:
public native boolean sendZeroCopy(ByteBuffer buffer, int len, int flags);
and allocated memory using ByteBuffer.allocateDirect()
Application publishes lot of data.
The problem is that jzmq tries to free memory on its own:
Socket.cpp
static
void s_delete_ref (void *ptr, void *hint)
{
    jzmq_zerocopy_t *free_hint = (jzmq_zerocopy_t *)hint;
    free_hint->env->DeleteGlobalRef(free_hint->ref_buffer);
    delete free_hint;
}
But jvm tries to deallocate memory also. It happens when XX:MaxDirectMemorySize limit reached and GC finalize Butebuffer objects. So my application crashes unexpectedly after some time (when enought data sent).

So i think it's reasonable to change javadocs - so users know that they need to suppress Butebuffer objects to be garbage collected...

### LINKED ISSUE #432: bug on ZeroCopySend
JNIEnv cannt be cached and used in another thread, it may cause jvm crush. I fix it like this , please check other code 
Socket.cpp
`typedef struct _jzmq_zerocopy_t {
 JavaVM *jvm;
 jobject ref_buffer;
 } jzmq_zerocopy_t;

static
 void s_delete_ref (void ptr, void *hint)
 {
 jzmq_zerocopy_t *free_hint = (jzmq_zerocopy_t *)hint;
 JNIEnv *env;
 free_hint->jvm->AttachCurrentThreadAsDaemon((void *)&env, NULL);
 env->DeleteGlobalRef(free_hint->ref_buffer);
 delete free_hint;
 }

#if ZMQ_VERSION >= ZMQ_MAKE_VERSION(3,0,0)
 static
 jboolean s_zerocopy_init (JNIEnv *env, zmq_msg_t *message, jobject obj, jint length)
 {
 jobject ref_buffer = env->NewGlobalRef(obj);
 jzmq_zerocopy_t *free_hint = new jzmq_zerocopy_t;
JavaVM *gs_jvm;  
env->GetJavaVM(&gs_jvm);

free_hint->jvm = gs_jvm;
free_hint->ref_buffer = ref_buffer;

jbyte* buf = (jbyte*) env->GetDirectBufferAddress(ref_buffer);

int rc = zmq_msg_init_data (message, buf, length, s_delete_ref, free_hint);
if (rc != 0) {
    int err = zmq_errno();
    raise_exception (env, err);
    return JNI_FALSE;
}
return JNI_TRUE;

}
`

### PR DESCRIPTION
**Pull request by comius**
Fixes #432
Fixes #419
Additionally fixes bug with concurrent access in ZLoop / synchronzation.

### CODE REVIEW

**Comment by colini** [comment]
I'm not sure ZLoop was ever meant to be thread safe.  Is it a valid use case to add/remove pollers from other threads?

**Comment by comius** [comment]
My usecase is: I'm processing in one ZLoop and then adding connections/pollers from another thread.
To workaround, one would need to open another pipe and use it to add pollers from within ZLoop.

**Comment by colini** [comment]
IME it is risky and/or difficult to add thread safety to a class that wasn't designed for it in the first place.  I'd recommend you use the workaround you described rather than make this change.

But if you want to do this, you need to guard both read and write access to the 'dirty' field.  Line 247 must synchronize on pollers before reading the dirty field.  Or make 'dirty' volatile.

**Comment by comius** [comment]
I agree it is difficult to add thread safety. With synchronization, the library will work the same as before, if it is used from single thread.

**Comment by comius** [comment]
Fixes #481

**Pull request closed without merging**
