### PR TITLE
Adds support for generating CURVE key pairs

### PR DESCRIPTION
**Pull request by djelenc**

### CODE REVIEW

**Comment by djelenc** [comment]
Hm, strange. Travis fails, but it runs ok on my machine. Allow me some time to take a look into this.

**Comment by djelenc** [comment]
Huh, interesting. It looks as if called zmqp functions (`zmq_curve_keypair`, `zmq_z85_encode`, `zmq_z85_decode`) are not defined.

What is the version of zmq that is run in travis?

**Comment by trevorbernard** [comment]
It's certainly an old version. I'll update the travis build to use a much newer version

**Comment by djelenc** [comment]
Also, in general, it seems that Travis is having a day off today ... :-)

**Pull request closed without merging**
